package olutrekisteri.test;
// Generated by ComTest BEGIN
import olutrekisteri.*;
import static org.junit.Assert.*;
import org.junit.*;
// Generated by ComTest END
import olutrekisteri.Olut.Vertailija;

/**
 * Test class made by ComTest
 * @version 2021.04.19 17:30:40 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class OlutTest {



  // Generated by ComTest BEGIN
  /** testGetKenttia33 */
  @Test
  public void testGetKenttia33() {    // Olut: 33
    Olut olut = new Olut(); 
    assertEquals("From: Olut line: 35", 6, olut.getKenttia()); 
    assertEquals("From: Olut line: 36", 1, olut.ekaKentta());
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testRekisteroi72 */
  @Test
  public void testRekisteroi72() {    // Olut: 72
    Olut olut1 = new Olut(); 
    assertEquals("From: Olut line: 74", 0, olut1.getOlutId()); 
    olut1.rekisteroi(); 
    Olut olut2 = new Olut(); 
    olut2.rekisteroi(); 
    int n1 = olut1.getOlutId(); 
    int n2 = olut2.getOlutId(); 
    assertEquals("From: Olut line: 80", n2-1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString104 */
  @Test
  public void testToString104() {    // Olut: 104
    Olut olut = new Olut(); 
    olut.taytaEsimTiedoilla(); 
    { String _l_=olut.toString(),_r_=".*|Cloudberry Saison.*|Pyyniking Brewing Company|.*"; if ( !_l_.matches(_r_) ) fail("From: Olut line: 107" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse120 */
  @Test
  public void testParse120() {    // Olut: 120
    Olut olut = new Olut(); 
    olut.parse("     4  |    Cloudberry Saison   |  Pyynikin Brewing Company"); 
    assertEquals("From: Olut line: 123", 4, olut.getOlutId()); 
    assertEquals("From: Olut line: 124", true, olut.toString().startsWith("4|Cloudberry Saison|Pyynikin Brewing Company|")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone141 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone141() throws CloneNotSupportedException {    // Olut: 141
    Olut olut = new Olut(); 
    olut.parse("     4  |    Cloudberry Saison   |  Pyynikin Brewing Company"); 
    Olut kopio = olut.clone(); 
    assertEquals("From: Olut line: 146", olut.toString(), kopio.toString()); 
    olut.parse("1|Cloudberry Saison|Pyynikin Brewing Company|saison|8.5|32.0"); 
    assertEquals("From: Olut line: 148", false, kopio.toString().equals(olut.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetNimi170 */
  @Test
  public void testGetNimi170() {    // Olut: 170
    Olut olut = new Olut(); 
    olut.taytaEsimTiedoilla(); 
    { String _l_=olut.getNimi(),_r_="Cloudberry Saison .*"; if ( !_l_.matches(_r_) ) fail("From: Olut line: 173" + " does not match: ["+ _l_ + "] != [" + _r_ + "]");}; 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetKysymys195 */
  @Test
  public void testGetKysymys195() {    // Olut: 195
    Olut olut = new Olut(); 
    assertEquals("From: Olut line: 197", "nimi", olut.getKysymys(1)); 
    assertEquals("From: Olut line: 198", "valmistaja", olut.getKysymys(2)); 
    assertEquals("From: Olut line: 199", "tyylilaji", olut.getKysymys(3)); 
    assertEquals("From: Olut line: 200", "", olut.getKysymys(10)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAnna220 */
  @Test
  public void testAnna220() {    // Olut: 220
    Olut olut = new Olut(); 
    olut.parse("     4  |    Cloudberry Saison   |  Pyynikin Brewing Company"); 
    assertEquals("From: Olut line: 223", "4", olut.anna(0)); 
    assertEquals("From: Olut line: 224", "Cloudberry Saison", olut.anna(1)); 
    assertEquals("From: Olut line: 225", "Pyynikin Brewing Company", olut.anna(2)); 
    assertEquals("From: Olut line: 226", "", olut.anna(3)); 
    assertEquals("From: Olut line: 227", "", olut.anna(10)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta249 */
  @Test
  public void testAseta249() {    // Olut: 249
    Olut o1 = new Olut(); 
    assertEquals("From: Olut line: 251", null, o1.aseta(1, "Cloudberry Saison")); 
    assertEquals("From: Olut line: 252", null, o1.aseta(3, "saison")); 
    assertEquals("From: Olut line: 253", "Pitää olla numero", o1.aseta(4, "kissa")); 
    assertEquals("From: Olut line: 254", null, o1.aseta(4, "5.5")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testGetAvain295 */
  @Test
  public void testGetAvain295() {    // Olut: 295
    Olut o1 = new Olut(); 
    o1.parse("1|Cloudberry Saison|Pyynikin Brewing Company|saison|8.5|32.0"); 
    assertEquals("From: Olut line: 298", "1", o1.getAvain(0)); 
    assertEquals("From: Olut line: 299", "Cloudberry Saison", o1.getAvain(1)); 
    assertEquals("From: Olut line: 300", "8.5", o1.getAvain(4)); 
    assertEquals("From: Olut line: 301", "", o1.getAvain(10)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testCompare361 */
  @Test
  public void testCompare361() {    // Olut: 361
    Olut o1 = new Olut(); o1.parse("1|Cloudberry Saison 2508|Pyynikin Brewing Company|saison|8.5|32.0"); 
    Olut o2 = new Olut(); o2.parse("2|Red|Teerenpeli|red ale|5.0|30.0"); 
    Olut o3 = new Olut(); o3.parse("3|Candy Beer Saga vol.1|Panimoyhtiö X|sour ale|5.5|42.0"); 
    Vertailija v1 = new Vertailija(0); 
    assertEquals("From: Olut line: 367", true, v1.compare(o1, o2) < 0); 
    assertEquals("From: Olut line: 368", true, v1.compare(o3, o1) > 0); 
    assertEquals("From: Olut line: 369", true, v1.compare(o2, o3) < 0); 
    Vertailija v2 = new Vertailija(1); 
    assertEquals("From: Olut line: 371", true, v2.compare(o1, o2) < 0); 
    assertEquals("From: Olut line: 372", true, v2.compare(o2, o3) > 0); 
    assertEquals("From: Olut line: 373", true, v2.compare(o1, o3) > 0); 
  } // Generated by ComTest END
}